platform :ios, '8.0'
target 'XuanMaoShopping' do
pod 'MJRefresh'
pod 'pop'
pod 'SVProgressHUD'
pod 'FDFullscreenPopGesture'
pod 'Masonry'
pod ‘UMengUShare/Social/ReducedWeChat'
pod ‘UMengUShare/Social/ReducedQQ'
pod ‘UMengUShare/Social/ReducedSina'
end
